apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "awx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "awx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: web
          image: "{{ .Values.awx_web.image.repository }}:{{ .Values.awx_web.image.tag }}"
          command:
            - /usr/bin/launch_awx.sh
          imagePullPolicy: {{ .Values.awx_web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: supervisor-socket
              mountPath: "/var/run/supervisor"
            - mountPath: /etc/tower
              name: {{ include "awx.fullname" . }}-application-config
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: {{ include "awx.fullname" . }}-application-config-nginx
            - name: {{ include "awx.fullname" . }}-application-credentials
              mountPath: "/etc/tower/conf.d/"
              readOnly: true
            - name: {{ include "awx.fullname" . }}-redis-socket
              mountPath: "/var/run/redis"
            - name: {{ include "awx.fullname" . }}-launch-awx-web
              mountPath: "/usr/bin/launch_awx.sh"
              subPath: "launch_awx.sh"
              readOnly: true
            - name: {{ include "awx.fullname" . }}-supervisor-web-config
              mountPath: "/supervisor.conf"
              subPath: supervisor.conf
              readOnly: true

            - name: {{ include "awx.fullname" . }}-supervisor-task-config
              mountPath: "/supervisor_task.conf"
              subPath: supervisor_task.conf
              readOnly: true
            - name: {{ include "awx.fullname" . }}-launch-awx-task
              mountPath: "/usr/bin/launch_awx_task.sh"
              subPath: "launch_awx_task.sh"
              readOnly: true
          env:
            - name: DATABASE_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DATABASE_NAME
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: DATABASE_HOST
              value: {{ .Values.postgresql.postgresqlHost }}
            - name: DATABASE_PORT
              value: {{ .Values.postgresql.postgresqlPort | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: MEMCACHED_HOST
              value: {{ include "awx.fullname" . }}-memcached
            - name: RABBITMQ_HOST
              value: {{ include "awx.fullname" . }}-rabbitmq
        - name: redis
          image: bitnami/redis:5.0.7-debian-9-r27
          imagePullPolicy: Always
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'
          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379
          volumeMounts:
            - name: {{ include "awx.fullname" . }}-redis-socket
              mountPath: "/var/run/redis"
            - name: {{ include "awx.fullname" . }}-redis-conf
              mountPath: "/opt/bitnami/redis/etc/redis.conf"
              subPath: "redis.conf"
        - name: task
          image: "{{ .Values.awx_task.image.repository }}:{{ .Values.awx_task.image.tag }}"
          imagePullPolicy: {{ .Values.awx_task.image.pullPolicy }}
          command:
            - /usr/bin/launch_awx_task.sh
          volumeMounts:
            - mountPath: /etc/tower
              name: {{ include "awx.fullname" . }}-application-config
            - name: {{ include "awx.fullname" . }}-redis-socket
              mountPath: "/var/run/redis"
            - name: {{ include "awx.fullname" . }}-launch-awx-web
              mountPath: "/usr/bin/launch_awx.sh"
              subPath: "launch_awx.sh"
              readOnly: true
            - name: {{ include "awx.fullname" . }}-supervisor-web-config
              mountPath: "/supervisor.conf"
              subPath: supervisor.conf
              readOnly: true

            - name: {{ include "awx.fullname" . }}-supervisor-task-config
              mountPath: "/supervisor_task.conf"
              subPath: supervisor_task.conf
              readOnly: true
            - name: {{ include "awx.fullname" . }}-launch-awx-task
              mountPath: "/usr/bin/launch_awx_task.sh"
              subPath: "launch_awx_task.sh"
              readOnly: true
          env:
            - name: DATABASE_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DATABASE_NAME
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: DATABASE_HOST
              value: {{ .Values.postgresql.postgresqlHost }}
            - name: DATABASE_PORT
              value: {{ .Values.postgresql.postgresqlPort | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: MEMCACHED_HOST
              value: {{ include "awx.fullname" . }}-memcached
            - name: RABBITMQ_HOST
              value: {{ include "awx.fullname" . }}-rabbitmq
            - name: AWX_ADMIN_USER
              value: {{ .Values.default_admin_user }}
            - name: AWX_ADMIN_PASSWORD
              value: {{ .Values.default_admin_password }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.hostAliases }}
    {{- with .Values.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.tolerations }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- end }}
      volumes:
        - name: supervisor-socket
          emptyDir: {}
        - name: {{ include "awx.fullname" . }}-redis-socket
          emptyDir: {}
        - name: {{ include "awx.fullname" . }}-application-config
          configMap:
            name: {{ include "awx.fullname" . }}-application-config
            items:
              - key: awx_settings
                path: settings.py
              - key: secret_key
                path: SECRET_KEY
        - name: {{ include "awx.fullname" . }}-application-config-nginx
          configMap:
            name: {{ include "awx.fullname" . }}-application-config
            items:
              - key: nginx_conf
                path: nginx.conf
        - name: "{{ include "awx.fullname" . }}-application-credentials"
          configMap:
            name: {{ include "awx.fullname" . }}-application-config
            items:
              - key: environment_sh
                path: 'environment.sh'
        - name: {{ include "awx.fullname" . }}-launch-awx-web
          configMap:
            name: {{ include "awx.fullname" . }}-launch-awx
            items:
              - key: launch-awx-web
                path: 'launch_awx.sh'
            defaultMode: 0755

        - name: {{ include "awx.fullname" . }}-launch-awx-task
          configMap:
            name: {{ include "awx.fullname" . }}-launch-awx
            items:
              - key: launch-awx-task
                path: 'launch_awx_task.sh'
            defaultMode: 0755
        - name: {{ include "awx.fullname" . }}-redis-conf
          configMap:
            name: {{ include "awx.fullname" . }}-redis-conf
            items:
              - key: redis.conf
                path: 'redis.conf'
        - name: {{ include "awx.fullname" . }}-supervisor-web-config
          configMap:
            name: {{ include "awx.fullname" . }}-supervisor-config
            items:
              - key: supervisor-web-config
                path: 'supervisor.conf'

        - name: {{ include "awx.fullname" . }}-supervisor-task-config
          configMap:
            name: {{ include "awx.fullname" . }}-supervisor-config
            items:
              - key: supervisor-task-config
                path: 'supervisor_task.conf'
