image:
  repository: honestica/kube-iptables-tailer
  tag: master-19
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Only one of the next configuration should be enabled
# iptablesLogPath: "/var/log/iptables.log"
# journalDirectory: "/var/log/journal"

iptablesLogPrefix: "calico-packet:"
kubeApiServicer: "https://kubernetes.default:443"

podAnnotations: {}
  # prometheus.io/scrape: "true"
  # prometheus.io/port: "9090"

rbac:
  create: true

serviceAccount:
  create: true
  name:

# Should alway enabled or you have to do manual iptable configuration on each host
calico:
  loggingEnable: true
  # check your apiversion with `kubectl api-versions`
  apiVersion: projectcalico.org/v3

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
