---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-bridge-svc
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/component: op-scim-bridge
spec:
  ports:
  - name: http
    port: {{ $.Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ $.Values.service.internalPort }}
  selector:
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/component: op-scim-bridge
  type: ClusterIP
