{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport.serviceAccountName" . }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- end -}}
